#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

namespace grip {

/**
* BlobPipe class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class BlobPipe {
	private:
		cv::Mat hsvThresholdOutput;
		std::vector<cv::KeyPoint> findBlobsOutput;
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void findBlobs(cv::Mat &, double , double [], bool , std::vector<cv::KeyPoint> &);

	public:
		BlobPipe();
		void Process(cv::Mat& source0);
		cv::Mat* GetHsvThresholdOutput();
		std::vector<cv::KeyPoint>* GetFindBlobsOutput();
};


} // end namespace grip


